---
- name: Deploy vmagent to docker container
  when: not vmagent_swarm_cluster or vm_swarm_manager is undefined
  block:
  - name: Ensure storage directory
    ansible.builtin.file:
      state: directory
      path: "{{ vmagent_storage_dir }}"
      mode: 0755
      owner: "{{ vmagent_uid }}"
      group: "{{ vmagent_gid }}"

  - name: Ensure scrape_configs directory
    ansible.builtin.file:
      state: directory
      path: "{{ vmagent_config_dir }}/scrape_configs"
      mode: 0755
      owner: "{{ vmagent_uid }}"
      group: "{{ vmagent_gid }}"

  - name: Show configuration
    ansible.builtin.debug:
      var: prometheus_config
    tags:
      - show_config

  - name: Ensure configuration file
    ansible.builtin.template:
      src: prometheus.yml.j2
      dest: "{{ vmagent_config_dir }}/prometheus.yml"
      mode: 0755
      owner: "{{ vmagent_uid }}"
      group: "{{ vmagent_gid }}"
    notify:
      - Check configuration
      - Reload vmagent

  - name: Find scrape_configs files
    ansible.builtin.find:
      paths: "{{ vmagent_config_dir }}/scrape_configs"
      patterns: "*.yml"
    register: list_of_scrape_files

  - name: Select names of scrape_config files
    ansible.builtin.set_fact:
      list_of_scrape_filenames: "{{ list_of_scrape_filenames | default([]) + [item.path | basename] }}"
    with_items: "{{ list_of_scrape_files.files }}"

  - name: Set list of names
    ansible.builtin.set_fact:
      list_of_filenames_to_add: "{{ list_of_filenames_to_add | default([]) + [item.filename] }}"
    with_items: "{{ vmagent_additional_configs | flatten }}"

  - name: Clear scrape_configs directory
    ansible.builtin.file:
      path: "{{ vmagent_config_dir }}/scrape_configs/{{ item }}"
      state: absent
    with_items: "{{ list_of_scrape_filenames | default([]) | difference(list_of_filenames_to_add | default([])) }}"
    notify:
      - Check configuration
      - Reload vmagent

  - name: Ensure additional configuration files
    ansible.builtin.copy:
      content: "{{ item.data | to_nice_yaml(indent=2) }}"
      dest: "{{ vmagent_config_dir }}/scrape_configs/{{ item.filename }}"
      mode: 0644
      owner: "{{ vmagent_uid }}"
      group: "{{ vmagent_gid }}"
    with_items: "{{ vmagent_additional_configs | flatten }}"
    notify:
      - Check configuration
      - Reload vmagent

  - name: Start docker vmagent container
    community.docker.docker_compose_v2:
      state: present
      project_name: vmagent
      definition:
        services:
          vmagent:
            image: "{{ vmagent_docker_image }}"
            container_name: "{{ vmagent_container_name }}"
            command: "{{ vmagent_command }}"
            ports: "{{ vmagent_ports }}"
            volumes:
              - "{{ vmagent_storage_dir }}:/vmagentdata"
              - "{{ vmagent_config_dir }}/prometheus.yml:/etc/prometheus/prometheus.yml"
              - "{{ vmagent_config_dir }}/scrape_configs:/etc/prometheus/scrape_configs"
              - "/var/run/docker.sock:/var/run/docker.sock:ro"
            hostname: "{{ vmagent_container_name }}"
            restart: always
            labels: "{{ vmagent_docker_labels }}"
            extra_hosts: "{{ vmagent_extra_hosts }}"
            user: "{{ vmagent_uid }}:{{ vmagent_gid }}"
            group_add:
              - "{{ vmagent_docker_group_id }}"
        networks:
          default:
            external: true
            name: "{{ vmagent_docker_network_name }}"

- name: Deploy vmagent to docker swarm
  delegate_to: "{{ vm_swarm_manager | default(omit) }}"
  when:
    - vmagent_swarm_cluster
    - vm_swarm_manager is defined
  block:
    - name: Ensure pip installation
      ansible.builtin.package:
        name: "python3-pip"
        state: present

    - name: Install newer version of pip itself
      ansible.builtin.pip:
        name: "pip"
        state: latest
        executable: pip3
      when:
        - ansible_facts['distribution'] | lower == "ubuntu"
        - ansible_facts['distribution_major_version'] | int != 24

    - name: Install jsondiff from pip
      ansible.builtin.pip:
        name: "jsondiff"
        state: present
        executable: pip3
      when:
        - ansible_facts['distribution'] | lower == "ubuntu"
        - ansible_facts['distribution_major_version'] | int != 24

    - name: Ensure jsondiff
      ansible.builtin.package:
        name: "python3-jsondiff"
        state: present
      when:
        - ansible_facts['distribution'] | lower == "ubuntu"
        - ansible_facts['distribution_major_version'] | int == 24

    - name: Check if config-file has changes
      community.docker.docker_config:
        name: vmagent-config
        data: "{{ prometheus_config | to_nice_yaml(indent=2) }}"
      check_mode: true
      register: config_changes
      run_once: true

    - name: Delete service
      community.docker.docker_swarm_service:
        state: absent
        name: "{{ vmagent_stack_name }}_vmagent"
      run_once: true
      when: config_changes.changed

    - name: Update config
      community.docker.docker_config:
        name: vmagent-config
        data: "{{ prometheus_config | to_nice_yaml(indent=2) }}"
        state: present
      run_once: true
      when: config_changes.changed

    - name: Deploy docker vmagent container in swarm
      community.docker.docker_stack:
        state: present
        name: "{{ vmagent_stack_name }}"
        with_registry_auth: true
        compose:
          - services:
              vmagent:
                image: "{{ vmagent_docker_image }}"
                command: "{{ vmagent_command }}"
                hostname: "{{ vmagent_container_name }}"
                labels: "{{ vmagent_docker_labels }}"
                ports: "{{ vmagent_ports }}"
                configs:
                  - source: vmagent-config
                    target: /etc/prometheus/prometheus.yml
                volumes:
                  - "/var/run/docker.sock:/var/run/docker.sock:ro"
                extra_hosts: "{{ vmagent_extra_hosts }}"
                deploy: "{{ vmagent_swarm_deploy }}"
                networks: "{{ vmagent_swarm_networks.keys() }}"
                user: "{{ vmagent_uid }}:{{ vmagent_gid }}"
            configs:
              vmagent-config:
                external: true
            networks: "{{ vmagent_swarm_networks }}"
      run_once: true

    - name: Get current service spec
      community.docker.docker_swarm_service_info:
        name: "{{ vmagent_stack_name }}_vmagent"
      register: service_info
      run_once: true

    - name: Add docker group if missing
      ansible.builtin.command:
        cmd: docker service update --group-add {{ vmagent_docker_group_id }} {{ vmagent_stack_name }}_vmagent
      run_once: true
      when: >
        vmagent_docker_group_id|string not in
        (service_info.Spec.TaskTemplate.ContainerSpec.Groups | default([]) | map('string') | list)
